---
title: "수상 및 펠로우십"
---

## 미국 

International Travel Award – $3,000 award to support international travel to present to a paper at a peer-reviewed conference (Annual Conference of the European Society of Criminology) from Criminology and Criminal Justice Program, The University of Texas at Dallas, Richardson, TX. (2026) 

Finalists, The Outstanding Student Organization of the Year Award from Dean’s Council, School of Economic, Political, and Policy Sciences, The University of Texas at Dallas, Richardson, TX. (2026) 

UTD Korean Alumni Scholarship from Korean Student Association, The University of Texas at Dallas, TX. (2024) 

## 대한민국 

Academic Excellence Scholarship for Freshmen from Korean National Police University, Asan, South Korea. (2020) 

Merit Scholarship from College of Social Sciences, Chung-Ang University, Seoul, South Korea. (2018) 

3rd Da Vinci Software Hackathon Contest Excellence Award from Da Vinci Software Education Institute, Chung-Ang University, Seoul, South Korea. (2018) 

1st On-campus Academic Conference (2nd Place) from College of Social Sciences, Chung-Ang University, Seoul, South Korea. (2018) 

National Digital Forensic Center (NDFC) “Scientific Investigation in the 4th Industrial Revolution Undergraduate/Graduate Student Idea Contest” Excellence Award from Supreme Prosecutors' Office of the Republic of Korea & National Research Foundation of Korea, Seoul, South Korea. (2018) 