---
title: "Teaching"
---

My goal as an educator is to help students move beyond memorizing concepts to critically examining how the criminal justice system operates, whom it affects, and how it might be improved. I view the criminology classroom as a space where students can connect academic knowledge and curiosity with real-world questions about crime, justice, and social responsibility based on evidence. Ultimately, I hope my students can leave my courses better prepared to evaluate information, engage thoughtfully with perspectives different from their own, and contribute to discussions about the criminal justice system. 

## Teaching Instructor 

- My syllabi are available upon request! 

CRIM 1301 Introduction to Criminal Justice (Undergraduate Level, In-person, Fall 26) 

CRIM 3303 Advanced Criminal Justice (Undergraduate Level, Co-teaching, In-person, Summer 26)

CRIM 3307 Immigration and Crime (Undergraduate Level, In-person, Spring 26) 

CRIM 3310 Youth Crime and Justice (Undergraduate Level, Co-teaching, Online, Summer 25)

CRIM 3310 Youth Crime and Justice (Undergraduate Level, In-Person, Fall 24) 

CRIM 3310 Youth Crime and Justice (Undergraduate Level, Co-teaching, Online, Summer 24)



## Teaching Assistant 

EPPS 6316 Applied Regression (Graduate Level, In-Person, Spring 25)

CRIM 4322 Senior Research Seminar (Undergraduate Level, In-Person, Spring 25)

CRIM 3302 Advanced Criminology (Undergraduate Level, Online, Spring 24)

CRIM 3302 Advanced Criminology (Undergraduate Level, Online, Fall 23)

